// Generated by CoffeeScript 1.3.3
(function() {
  var DateLabeler, generateYearLabels, getAllDates, makeYearLabel, writeLabel;

  $(function() {
    return generateYearLabels();
  });

  generateYearLabels = function() {
    var dl, rows;
    dl = new DateLabeler;
    rows = getAllDates();
    dl.markFirstInstanceOfEachYear(rows);
    return rows.map(writeLabel);
  };

  getAllDates = function() {
    return ($('td.date')).map(function() {
      return {
        datestring: ($(this)).html(),
        element: this
      };
    });
  };

  writeLabel = function() {
    var element;
    element = this.element;
    if (this.label_before != null) {
      return ($(element)).parent().before(makeYearLabel(this.label_before));
    }
  };

  makeYearLabel = function(year) {
    return "<div class=\"year_label\">" + year + "</div>";
  };

  DateLabeler = (function() {

    function DateLabeler() {}

    DateLabeler.prototype.markFirstInstanceOfEachYear = function(row_list) {
      var date, first, newest_label, row, _i, _len, _results;
      first = row_list[0];
      this.mark(first);
      newest_label = first.label_before;
      _results = [];
      for (_i = 0, _len = row_list.length; _i < _len; _i++) {
        row = row_list[_i];
        date = this.parse(row.datestring);
        if (date !== newest_label) {
          newest_label = date;
          _results.push(this.mark(row));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    DateLabeler.prototype.mark = function(row) {
      var year;
      year = this.parse(row.datestring);
      return row.label_before = year;
    };

    DateLabeler.prototype.parse = function(date) {
      return date.split(",").pop().trim();
    };

    return DateLabeler;

  })();

}).call(this);
