// Generated by CoffeeScript 1.3.3
(function() {
  var DateLabeler, generateYearLabels, getAllDates, makeYearLabel, writeLabel;

  $(function() {
    return generateYearLabels();
  });

  generateYearLabels = function() {
    var all_rows, dl, rows_to_label;
    dl = new DateLabeler;
    all_rows = getAllDates();
    rows_to_label = dl.firstInstanceOfEachYear(all_rows);
    return rows_to_label.map(writeLabel);
  };

  getAllDates = function() {
    return ($('td.date')).map(function() {
      return {
        datestring: ($(this)).html(),
        element: this
      };
    });
  };

  writeLabel = function(row) {
    var element;
    element = row.element;
    return ($(element)).parent().before(makeYearLabel(row.label_before));
  };

  makeYearLabel = function(year) {
    return "<div class=\"year_label\">" + year + "</div>";
  };

  DateLabeler = (function() {

    function DateLabeler() {}

    DateLabeler.prototype.firstInstanceOfEachYear = function(rows) {
      var date, labeled_rows, newest_label, row, _i, _len;
      newest_label = "";
      labeled_rows = [];
      for (_i = 0, _len = rows.length; _i < _len; _i++) {
        row = rows[_i];
        date = this.parse(row.datestring);
        if (date !== newest_label) {
          newest_label = date;
          labeled_rows.push(this.labeled(row));
        }
      }
      return labeled_rows;
    };

    DateLabeler.prototype.labeled = function(row) {
      var year;
      year = this.parse(row.datestring);
      return {
        element: row.element,
        label_before: year
      };
    };

    DateLabeler.prototype.parse = function(date) {
      return date.split(",").pop().trim();
    };

    return DateLabeler;

  })();

}).call(this);
